// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt1QkeLtQhWP-y5gxrOXHYshWUdi5l-AY',
    appId: '1:294895503490:android:7fdf1f17499aeb677bcc9b',
    messagingSenderId: '294895503490',
    projectId: 'mx-companion-v2',
    storageBucket: 'mx-companion-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xWFW_CJfk82CjxNBjSKYsDWgSu81LHU',
    appId: '1:294895503490:ios:60b010241e130f5f7bcc9b',
    messagingSenderId: '294895503490',
    projectId: 'mx-companion-v2',
    storageBucket: 'mx-companion-v2.appspot.com',
    androidClientId: '294895503490-e4eem1tc2cq3hqnlg2flpvisj5cpenn1.apps.googleusercontent.com',
    iosClientId: '294895503490-5dunnku6vprua2les16hifsq5os7c2t7.apps.googleusercontent.com',
    iosBundleId: 'io.prodigy.mxCompanionV2',
  );
}
