// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZB_ary9kNcMSAtccuUPIXK3DJA8gch0',
    appId: '1:154967308722:web:3166b4e0efaff8a1524cab',
    messagingSenderId: '154967308722',
    projectId: 'mx-companion',
    authDomain: 'mx-companion.firebaseapp.com',
    storageBucket: 'mx-companion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOJowvTuwKu2axdHsH9p4Om4hgHLvAN4',
    appId: '1:154967308722:android:d5d20d08858c3c04524cab',
    messagingSenderId: '154967308722',
    projectId: 'mx-companion',
    storageBucket: 'mx-companion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwx6U1yhY-iuA6HCdXbR79XMoktuBSC0',
    appId: '1:154967308722:ios:a3761fb25ab0f297524cab',
    messagingSenderId: '154967308722',
    projectId: 'mx-companion',
    storageBucket: 'mx-companion.appspot.com',
    iosClientId: '154967308722-lebav893r146c5bbr9fusobdl28nl25t.apps.googleusercontent.com',
    iosBundleId: 'io.prodigy.mxCompanion',
  );
}
